export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVING_INGREDIENTS = 'REMOVING_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BUGRGER_START = 'PURCHASE_BUGRGER_START';
export const PURCHASE_BUGRGER_SUCCESS = 'PURCHASE_BUGRGER_SUCCESS';
export const PURCHASE_BUGRGER_FAIL = 'PURCHASE_BUGRGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
